version: '2'

services:
  app:
    build: .
    ports:
      - '8100:8100'
      - '35729:35729'
      - '53703:53703'
    expose:
      - "8100"
      - "35729"
      - "53703"
    env_file:
      - '.env-docker'
    command: ionic serve
    volumes:
      - './src:/app/src'
